let BASE_URL = "http://localhost:7171";
let BASE_USER_SERVICE_URL = "http://localhost:9002";
let BASE_SECTOR_SERVICE_URL = "http://localhost:9001";
let BASE_WORK_SERVICE_URL = "http://localhost:9007";
switch (process.env.NODE_ENV) {
  case "development":
    BASE_URL = "http://localhost:7171";
    break;

  default:
    break;
}
const USER_BASE_PATH = "users";
export const USER_ENDPOINTS = {
  AUTHENTICATE: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/authenticate`,
  GET_USER: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/simpleUser`,
  GET_USER_BY_USERNAME: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/user`,
  GET_USER_WITH_SECTOR: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}`,
  GET_ALL_USERS: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/all`,
  GET_ALL_USERS_IN_SECTOR: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/all/sector`,
  GET_ALL_USERS_IN_COMPANY: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/all/company`,
  SET_WORK_VISIBLE_FOR_USER: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/setWorkVisible`,
  SAVE_USER: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/save`,
  GET_USERS_BY_USERNAME: `${BASE_USER_SERVICE_URL}/${USER_BASE_PATH}/by`,
};

const ARRANGEMENT_BASE_PATH = "arrangements";
export const ARRANGEMENT_ENDPOINTS = {
  SAVE_NEW_ARRANGEMENT: `${BASE_USER_SERVICE_URL}/${ARRANGEMENT_BASE_PATH}`,
  GET_ALL_ARRANGEMENTS_FOR_USER: `${BASE_USER_SERVICE_URL}/${ARRANGEMENT_BASE_PATH}/all`,
  ADD_PARTICIPANT_TO_ARRANGEMENT: `${BASE_USER_SERVICE_URL}/${ARRANGEMENT_BASE_PATH}/addParticipant`,
  REMOVE_PARTICIPANT_FROM_ARRANGEMENT: `${BASE_USER_SERVICE_URL}/${ARRANGEMENT_BASE_PATH}/removeParticipant`,
};

const WORK_BASE_PATH = "work";
export const WORK_ENDPOINTS = {
  SAVE_TASK: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}`,
  GET_ALL_TASKS: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}/all`,
  REMOVE_TASK: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}/remove`,
  GET_TASK_WITH_USER_FOR_USER: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}`,
  GET_TASKS_FOR_USER: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}/tasks`,
  GET_TASK_WITH_FEEDBACK_LIST: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}`,
  SET_TASK_TO_FINISHED: `${BASE_WORK_SERVICE_URL}/${WORK_BASE_PATH}`,
};

const SECTOR_BASE_PATH = "sector";
export const SECTOR_ENDPOINTS = {
  SAVE_SECTOR: `${BASE_SECTOR_SERVICE_URL}/${SECTOR_BASE_PATH}/`,
  FIND_BY_ID: `${BASE_SECTOR_SERVICE_URL}/${SECTOR_BASE_PATH}`,
  GET_ALL_SECTORS: `${BASE_SECTOR_SERVICE_URL}/sector/all`,
  DELETE_SECTOR: `${BASE_SECTOR_SERVICE_URL}/${SECTOR_BASE_PATH}/delete`,
  GET_OFFERED_SERVICES_FOR_SECTOR: `${BASE_SECTOR_SERVICE_URL}/${SECTOR_BASE_PATH}/services`,
  AUTHENTICATE: `${BASE_SECTOR_SERVICE_URL}/${SECTOR_BASE_PATH}/authenticate`,
};

const COMPANY_BASE_PATH = "company";
export const COMPANY_ENDPOINTS = {
  SAVE_NEW_COMPANY: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}/`,
  FIND_COMPANY_BY_ID: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}`,
  DELETE_COMPANY_BY_ID: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}`,
  DELETE_SECTOR_FROM_COMPANY: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}`,
  ADD_SECTOR_TO_COMPANY: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}`,
  GET_OFFERED_SERVICES_FOR_COMPANY: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}/services`,
  GET_COMPANIES_FOR_NEEDED_SERVICE: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}/serviceNeeded`,
  GET_ALL_COMPANIES: `${BASE_SECTOR_SERVICE_URL}/${COMPANY_BASE_PATH}/all`,
};

const FEEDBACK_BASE_PATH = "feedback";
const FEEDBACK_USER_BASE_PATH = `${FEEDBACK_BASE_PATH}/user`;
const FEEDBACK_TASK_BASE_PATH = `${FEEDBACK_BASE_PATH}/task`;
const FEEDBACK_ARRANGEMENT_BASE_PATH = `${FEEDBACK_BASE_PATH}/arrangement`;
export const FEEDBACK_ENDPOINTS = {
  //USER FEEDBACK
  CREATE_USER_FEEDBACK: `${BASE_URL}/${FEEDBACK_USER_BASE_PATH}`,
  GET_USER_FEEDBACK: `${BASE_URL}/${FEEDBACK_USER_BASE_PATH}/for`,
  GET_USER_FEEDBACK_FROM: `${BASE_URL}/${FEEDBACK_USER_BASE_PATH}/from`,
  GET_ALL_USER_FEEDBACKS: `${BASE_URL}/${FEEDBACK_USER_BASE_PATH}/all`,
  //TASK FEEDBACK
  CREATE_TASK_FEEDBACK: `${BASE_URL}/${FEEDBACK_TASK_BASE_PATH}`,
  GET_TASK_FEEDBACK: `${BASE_URL}/${FEEDBACK_TASK_BASE_PATH}/for`,
  GET_ALL_TASK_FEEDBACKS: `${BASE_URL}/${FEEDBACK_TASK_BASE_PATH}/all`,
  //ARRANGEMENT FEEDBACK
  CREATE_ARRANGEMENT_FEEDBACK: `${BASE_URL}/${FEEDBACK_ARRANGEMENT_BASE_PATH}`,
  GET_ARRANGEMENT_FEEDBACK: `${BASE_URL}/${FEEDBACK_ARRANGEMENT_BASE_PATH}/for`,
  GET_ALL_ARRANGEMENT_FEEDBACKS: `${BASE_URL}/${FEEDBACK_ARRANGEMENT_BASE_PATH}/all`,
};
