let BASE_URL = "http://localhost:7171";
switch (process.env.NODE_ENV) {
  case "development":
    BASE_URL = "http://localhost:7171";
    break;

  default:
    break;
}
const USER_BASE_PATH = "users";
export const USER_ENDPOINTS = {
  AUTHENTICATE: "${BASE_URL}/${USER_BASE_BATH}/authenticate",
  GET_USER: "${BASE_URL}/${USER_BASE_BATH}/simpleUser",
  GET_USER_BY_USERNAME: "${BASE_URL}/${USER_BASE_BATH}/user",
  GET_USER_WITH_SECTOR: "${BASE_URL}/${USER_BASE_BATH}",
  GET_ALL_USERS: "${BASE_URL}/${USER_BASE_BATH}/all",
  GET_ALL_USERS_IN_SECTOR: "${BASE_URL}/${USER_BASE_BATH}/all/sector",
  GET_ALL_USERS_IN_COMPANY: "${BASE_URL}/${USER_BASE_BATH}/all/company",
  SET_WORK_VISIBLE_FOR_USER: "${BASE_URL}/${USER_BASE_BATH}/setWorkVisible",
  SAVE_USER: "${BASE_URL}/${USER_BASE_BATH}/save",
};

const ARRANGEMENT_BASE_PATH = "arrangements";
export const ARRANGEMENT_ENDPOINTS = {
  SAVE_NEW_ARRANGEMENT: "${BASE_URL}/${ARRANGEMENT_BASE_PATH}",
  GET_ALL_ARRANGEMENTS_FOR_USER: "${BASE_URL}/${ARRANGEMENT_BASE_PATH}/all",
  ADD_PARTICIPANT_TO_ARRANGEMENT:
    "${BASE_URL}/${ARRANGEMENT_BASE_PATH}/addParticipant",
  REMOVE_PARTICIPANT_FROM_ARRANGEMENT:
    "${BASE_URL}/${ARRANGEMENT_BASE_PATH}/removeParticipant",
};

const WORK_BASE_PATH = "work";
export const WORK_ENDPOINTS = {
  SAVE_TASK: "${BASE_URL}/${WORK_BASE_PATH}",
  GET_ALL_TASKS: "${BASE_URL}/${WORK_BASE_PATH}/all",
  REMOVE_TASK: "${BASE_URL}/${WORK_BASE_PATH}/remove",
  GET_TASK_WITH_USER_FOR_USER: "${BASE_URL}/${WORK_BASE_PATH}",
  GET_TASKS_FOR_USER: "${BASE_URL}/${WORK_BASE_PATH}/tasks",
  GET_TASK_WITH_FEEDBACK_LIST: "${BASE_URL}/${WORK_BASE_PATH}",
  SET_TASK_TO_FINISHED: "${BASE_URL}/${WORK_BASE_PATH}",
};
